### ISSUE TITLE
Connection thread safety?

### ISSUE THREAD

**Issue by collinhundley** [vapor/mysql#4]
In the README it says this:

`... a single connection cannot be used on more than one thread`

But in the documentation for `Database.makeConnection()` it says:

`Creates a new thread-safe connection to the database that can be reused between executions.`

Is `Connection` thread safe or is it not? The fact that `makeConnection()` is called before each query by defaults suggests that it probably isn't.

Establishing a new connection with the db for each query is wasteful; how can we update `Connection` to be totally thread safe? I don't have a very deep knowledge of the underlying C library, but based on the docs it looks like it should support multithreaded environments just fine. So which part currently isn't thread safe? `cConnection` shouldn't ever be mutated so I must be missing something.

**Comment by tannernelson** [comment]
The documentation for that method could be a little bit better. I will update it. 

Basically MySQL only supports one connection per thread. So if your app is not multithreaded, just create one connection using makeConnection and then pass that as the third parameter to all of your calls. Or, you can make a new connection for each thread and reuse that connection in the thread. 

The reason I chose to make a new connection every time by default is because using the same connection on multiple threads will crash with a fatal error. I'd rather have better performance be opt in than risk people's programs crashing if they don't understand how to work with threading properly.

**Comment by collinhundley** [comment]
That makes sense. However, I definitely think it's important to support multithreading without having to reconnect constantly. Most web servers written in Swift will be multithreaded, so I'm sure it's a common requirement.

Connection pooling seems like the logical solution. You say that using the same connection on multiple threads will cause a crash... I'm assuming by that you mean *unsynchronized* access, right? Unless there's something strange about the C library that I'm missing, we should be able to share connections across threads as long as we synchronize it properly. It shouldn't be too hard with GCD. What do you think?

**Comment by tannernelson** [comment]
Yes, I do mean unsynchronized access. I agree it should be easy to re-use the same connection, but I also think it should remain the default to create a new connection. Unless we use GCD internally to synchronize access. But I think that is beyond the scope of this simple wrapper.
