### ISSUE TITLE
Query data in different order then table order

### ISSUE THREAD

**Issue by HDsign** [vapor/mysql#65]
Most of the data returned after doing a query is in a different order then the data is in the database.

**Comment by collinhundley** [comment]
@HDsign what do you mean by different order than the database? MySQL's storage system is extremely complex, and as far as I'm aware there isn't any particular "order" that can be determined.

**Comment by HDsign** [comment]
Well if the table structure is like this:

* id
* name
* company_id
* created_at

The query `select * from users` gives a dataset in this order:

* name
* company_id
* id
* created_at

**Comment by collinhundley** [comment]
Oh you mean the fields.  Where are you getting this order?  The results of `database.execute()` are dictionaries.

**Comment by HDsign** [comment]
Yes `database.execute()`

**Comment by collinhundley** [comment]
If the results are a `Dictionary`, how do you know the order of the fields?

You just subscript the results like this: `let id = result["id"]?.string`, so order shouldn't matter.

**Comment by HDsign** [comment]
Yeah in that case your right.
I want to show the data fetch from the query in a tableView, create the columns and cell dynamically.

**Comment by HDsign** [comment]
Without knowing

**Comment by sahandnayebaziz** [comment]
Ah, I see. I'm thinking. Even if there were a way to make this package create the dictionary ensuring the keys are inserted initially in the same order as the table declaration, as soon as it's done we lose any guarantee of order since it is a dictionary.

This isn't a solution to the ordering problem, but maybe you can make the columns reorderable? I've been using a macOS desktop client called [Querious](http://www.araelium.com/querious/) and I reorder columns all the time after queries to move certain columns closer together so I can compare or move, say, the only column I care about in that moment all the way to the front.

I imagine all MySQL drivers in Swift today and into the future will use dictionaries for results. The popular [node driver](https://github.com/mysqljs/mysql) that I've used doesn't guarantee order either.  Depending on what you're doing, there might be a different solution to your issue :)

**Comment by collinhundley** [comment]
@sahandnayebaziz is right, there's currently no way to get results in any kind of order.

Technically it *is* possible, but it would complicate the API and I'm not sure how many people would have a use for it. If you want to write a custom implementation, take a look at `Connection.swift` - especially lines 114 - 136.

**Comment by HDsign** [comment]
Okay thank you guys for your time, I'll try to implement it myself. 👍
